// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyLink.Api.Data;

#nullable disable

namespace StudyLink.Api.Migrations
{
    [DbContext(typeof(StudyLinkDbContext))]
    partial class StudyLinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyLink.Api.Models.Commento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("integer");

                    b.Property<int>("MittenteId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Orario")
                        .HasColumnType("interval");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Valutazione")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("MittenteId");

                    b.ToTable("Commenti");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeLuogo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NumeroPosti")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Orario")
                        .HasColumnType("interval");

                    b.Property<int>("OrganizzatoreId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoLuogo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizzatoreId");

                    b.ToTable("Eventi");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Messaggio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Orario")
                        .HasColumnType("interval");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Messaggi");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Prenotazione", b =>
                {
                    b.Property<int>("UtenteId")
                        .HasColumnType("integer");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Orario")
                        .HasColumnType("interval");

                    b.HasKey("UtenteId", "EventoId");

                    b.HasIndex("EventoId");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Profilo", b =>
                {
                    b.Property<int>("UtenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorsoDiStudi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImmagineProfilo")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UtenteId");

                    b.ToTable("Profili");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Commento", b =>
                {
                    b.HasOne("StudyLink.Api.Models.Utente", "Destinatario")
                        .WithMany("CommentiRicevuti")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyLink.Api.Models.Utente", "Mittente")
                        .WithMany("CommentiInviati")
                        .HasForeignKey("MittenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Mittente");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Evento", b =>
                {
                    b.HasOne("StudyLink.Api.Models.Utente", "Organizzatore")
                        .WithMany("EventiOrganizzati")
                        .HasForeignKey("OrganizzatoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizzatore");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Messaggio", b =>
                {
                    b.HasOne("StudyLink.Api.Models.Evento", "Evento")
                        .WithMany("Messaggi")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyLink.Api.Models.Utente", "Utente")
                        .WithMany("Messaggi")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Prenotazione", b =>
                {
                    b.HasOne("StudyLink.Api.Models.Evento", "Evento")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyLink.Api.Models.Utente", "Utente")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Profilo", b =>
                {
                    b.HasOne("StudyLink.Api.Models.Utente", "Utente")
                        .WithOne("Profilo")
                        .HasForeignKey("StudyLink.Api.Models.Profilo", "UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Evento", b =>
                {
                    b.Navigation("Messaggi");

                    b.Navigation("Prenotazioni");
                });

            modelBuilder.Entity("StudyLink.Api.Models.Utente", b =>
                {
                    b.Navigation("CommentiInviati");

                    b.Navigation("CommentiRicevuti");

                    b.Navigation("EventiOrganizzati");

                    b.Navigation("Messaggi");

                    b.Navigation("Prenotazioni");

                    b.Navigation("Profilo");
                });
#pragma warning restore 612, 618
        }
    }
}
