// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyLink.Backend.Data;

#nullable disable

namespace StudyLink.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527132027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyLink.Backend.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventoId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Commento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("integer");

                    b.Property<int>("MittenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Valutazione")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("MittenteId");

                    b.ToTable("Commenti");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndirizzoNomeLuogo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IndirizzoVia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NumeroPosti")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Orario")
                        .HasColumnType("interval");

                    b.Property<int>("OrganizzatoreId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDiLuogo")
                        .HasColumnType("integer");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizzatoreId");

                    b.ToTable("Eventi");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Messaggio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataInvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MittenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("MittenteId");

                    b.ToTable("Messaggi");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Prenotazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<int>("UtenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CorsoDiStudi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Immagine")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Chat", b =>
                {
                    b.HasOne("StudyLink.Backend.Models.Evento", "Evento")
                        .WithOne("Chat")
                        .HasForeignKey("StudyLink.Backend.Models.Chat", "EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Commento", b =>
                {
                    b.HasOne("StudyLink.Backend.Models.Utente", "Destinatario")
                        .WithMany("CommentiRicevuti")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyLink.Backend.Models.Utente", "Mittente")
                        .WithMany("CommentiInviati")
                        .HasForeignKey("MittenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Mittente");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Evento", b =>
                {
                    b.HasOne("StudyLink.Backend.Models.Utente", "Organizzatore")
                        .WithMany("EventiCreati")
                        .HasForeignKey("OrganizzatoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizzatore");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Messaggio", b =>
                {
                    b.HasOne("StudyLink.Backend.Models.Chat", "Chat")
                        .WithMany("Messaggi")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyLink.Backend.Models.Utente", "Mittente")
                        .WithMany("Messaggi")
                        .HasForeignKey("MittenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Mittente");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Prenotazione", b =>
                {
                    b.HasOne("StudyLink.Backend.Models.Evento", "Evento")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyLink.Backend.Models.Utente", "Utente")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Chat", b =>
                {
                    b.Navigation("Messaggi");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Evento", b =>
                {
                    b.Navigation("Chat");

                    b.Navigation("Prenotazioni");
                });

            modelBuilder.Entity("StudyLink.Backend.Models.Utente", b =>
                {
                    b.Navigation("CommentiInviati");

                    b.Navigation("CommentiRicevuti");

                    b.Navigation("EventiCreati");

                    b.Navigation("Messaggi");

                    b.Navigation("Prenotazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
